package br.com.furb.tagarela.model;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import br.com.furb.tagarela.model.UserDao;
import br.com.furb.tagarela.model.CategoryDao;
import br.com.furb.tagarela.model.SymbolDao;
import br.com.furb.tagarela.model.PlanDao;
import br.com.furb.tagarela.model.SymbolPlanDao;
import br.com.furb.tagarela.model.GroupPlanDao;
import br.com.furb.tagarela.model.GroupPlanRelationshipDao;
import br.com.furb.tagarela.model.ObservationDao;
import br.com.furb.tagarela.model.SymbolHistoricDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 13): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 13;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        UserDao.createTable(db, ifNotExists);
        CategoryDao.createTable(db, ifNotExists);
        SymbolDao.createTable(db, ifNotExists);
        PlanDao.createTable(db, ifNotExists);
        SymbolPlanDao.createTable(db, ifNotExists);
        GroupPlanDao.createTable(db, ifNotExists);
        GroupPlanRelationshipDao.createTable(db, ifNotExists);
        ObservationDao.createTable(db, ifNotExists);
        SymbolHistoricDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        UserDao.dropTable(db, ifExists);
        CategoryDao.dropTable(db, ifExists);
        SymbolDao.dropTable(db, ifExists);
        PlanDao.dropTable(db, ifExists);
        SymbolPlanDao.dropTable(db, ifExists);
        GroupPlanDao.dropTable(db, ifExists);
        GroupPlanRelationshipDao.dropTable(db, ifExists);
        ObservationDao.dropTable(db, ifExists);
        SymbolHistoricDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(UserDao.class);
        registerDaoClass(CategoryDao.class);
        registerDaoClass(SymbolDao.class);
        registerDaoClass(PlanDao.class);
        registerDaoClass(SymbolPlanDao.class);
        registerDaoClass(GroupPlanDao.class);
        registerDaoClass(GroupPlanRelationshipDao.class);
        registerDaoClass(ObservationDao.class);
        registerDaoClass(SymbolHistoricDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
