package br.com.furb.tagarela.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table OBSERVATION.
 */
public class Observation {

    private java.util.Date date;
    private String observation;
    private Long serverID;
    private Integer tutorID;
    private Integer userID;
    private Long id;
    private Boolean isSynchronized;

    public Observation() {
    }

    public Observation(Long id) {
        this.id = id;
    }

    public Observation(java.util.Date date, String observation, Long serverID, Integer tutorID, Integer userID, Long id, Boolean isSynchronized) {
        this.date = date;
        this.observation = observation;
        this.serverID = serverID;
        this.tutorID = tutorID;
        this.userID = userID;
        this.id = id;
        this.isSynchronized = isSynchronized;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public String getObservation() {
        return observation;
    }

    public void setObservation(String observation) {
        this.observation = observation;
    }

    public Long getServerID() {
        return serverID;
    }

    public void setServerID(Long serverID) {
        this.serverID = serverID;
    }

    public Integer getTutorID() {
        return tutorID;
    }

    public void setTutorID(Integer tutorID) {
        this.tutorID = tutorID;
    }

    public Integer getUserID() {
        return userID;
    }

    public void setUserID(Integer userID) {
        this.userID = userID;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean getIsSynchronized() {
        return isSynchronized;
    }

    public void setIsSynchronized(Boolean isSynchronized) {
        this.isSynchronized = isSynchronized;
    }

}
