package br.com.furb.tagarela.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SYMBOL_PLAN.
 */
public class SymbolPlan {

    private Long serverID;
    private Long planServerID;
    private Long planLocalID;
    private Long symbolServerID;
    private Long symbolLocalID;
    private Integer position;
    private Boolean isSynchronized;
    private Long id;

    public SymbolPlan() {
    }

    public SymbolPlan(Long id) {
        this.id = id;
    }

    public SymbolPlan(Long serverID, Long planServerID, Long planLocalID, Long symbolServerID, Long symbolLocalID, Integer position, Boolean isSynchronized, Long id) {
        this.serverID = serverID;
        this.planServerID = planServerID;
        this.planLocalID = planLocalID;
        this.symbolServerID = symbolServerID;
        this.symbolLocalID = symbolLocalID;
        this.position = position;
        this.isSynchronized = isSynchronized;
        this.id = id;
    }

    public Long getServerID() {
        return serverID;
    }

    public void setServerID(Long serverID) {
        this.serverID = serverID;
    }

    public Long getPlanServerID() {
        return planServerID;
    }

    public void setPlanServerID(Long planServerID) {
        this.planServerID = planServerID;
    }

    public Long getPlanLocalID() {
        return planLocalID;
    }

    public void setPlanLocalID(Long planLocalID) {
        this.planLocalID = planLocalID;
    }

    public Long getSymbolServerID() {
        return symbolServerID;
    }

    public void setSymbolServerID(Long symbolServerID) {
        this.symbolServerID = symbolServerID;
    }

    public Long getSymbolLocalID() {
        return symbolLocalID;
    }

    public void setSymbolLocalID(Long symbolLocalID) {
        this.symbolLocalID = symbolLocalID;
    }

    public Integer getPosition() {
        return position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }

    public Boolean getIsSynchronized() {
        return isSynchronized;
    }

    public void setIsSynchronized(Boolean isSynchronized) {
        this.isSynchronized = isSynchronized;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

}
