package br.com.furb.tagarela.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table GROUP_PLAN.
 */
public class GroupPlan {

    private Integer serverID;
    private Integer hunterID;
    private Integer preyID;
    private String name;
    private String customText;

    public GroupPlan() {
    }

    public GroupPlan(Integer serverID, Integer hunterID, Integer preyID, String name, String customText) {
        this.serverID = serverID;
        this.hunterID = hunterID;
        this.preyID = preyID;
        this.name = name;
        this.customText = customText;
    }

    public Integer getServerID() {
        return serverID;
    }

    public void setServerID(Integer serverID) {
        this.serverID = serverID;
    }

    public Integer getHunterID() {
        return hunterID;
    }

    public void setHunterID(Integer hunterID) {
        this.hunterID = hunterID;
    }

    public Integer getPreyID() {
        return preyID;
    }

    public void setPreyID(Integer preyID) {
        this.preyID = preyID;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCustomText() {
        return customText;
    }

    public void setCustomText(String customText) {
        this.customText = customText;
    }

}
