package br.com.furb.tagarela.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table GROUP_PLAN_RELATIONSHIP.
 */
public class GroupPlanRelationship {

    private Integer serverID;
    private Integer groupID;
    private Integer planID;

    public GroupPlanRelationship() {
    }

    public GroupPlanRelationship(Integer serverID, Integer groupID, Integer planID) {
        this.serverID = serverID;
        this.groupID = groupID;
        this.planID = planID;
    }

    public Integer getServerID() {
        return serverID;
    }

    public void setServerID(Integer serverID) {
        this.serverID = serverID;
    }

    public Integer getGroupID() {
        return groupID;
    }

    public void setGroupID(Integer groupID) {
        this.groupID = groupID;
    }

    public Integer getPlanID() {
        return planID;
    }

    public void setPlanID(Integer planID) {
        this.planID = planID;
    }

}
